# Generated by Django 5.1.15 on 2026-09-02 20:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0002_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "cadence_days",
                    models.PositiveIntegerField(
                        help_text="How many days between one occurrence and the next.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "estimated_minutes",
                    models.PositiveIntegerField(
                        help_text="Rough time one occurrence takes.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Very easy"),
                            (2, "Easy"),
                            (3, "Moderate"),
                            (4, "Hard"),
                            (5, "Very hard"),
                        ],
                        default=3,
                    ),
                ),
                ("allows_multiple_contributors", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chores",
                        to="chores.household",
                    ),
                ),
                (
                    "primary_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_chores",
                        to="chores.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
