# Generated by Django 5.1.15 on 2026-09-02 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0004_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoreOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="chores.chore",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chore", "due_date"),
                        name="unique_occurrence_per_chore_per_date",
                    )
                ],
            },
        ),
    ]
