# Generated by Django 5.1.15 on 2026-09-02 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0005_choreoccurrence"),
    ]

    operations = [
        migrations.CreateModel(
            name="Completion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How long it actually took, if recorded.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "actual_effort",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Very easy"),
                            (2, "Easy"),
                            (3, "Moderate"),
                            (4, "Hard"),
                            (5, "Very hard"),
                        ],
                        help_text="How hard it actually was, on the chore difficulty scale.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completions",
                        to="chores.membership",
                    ),
                ),
                (
                    "occurrence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion",
                        to="chores.choreoccurrence",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
    ]
