# Generated by Django 5.1.15 on 2026-09-02 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0006_completion"),
    ]

    operations = [
        migrations.AddField(
            model_name="choreoccurrence",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The member who volunteered to do this occurrence. Advisory only - it never changes the chore's primary owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_occurrences",
                to="chores.membership",
            ),
        ),
        migrations.CreateModel(
            name="ContributionCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workload_value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit",
                        to="chores.completion",
                    ),
                ),
                (
                    "helper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits_as_helper",
                        to="chores.membership",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits_as_owner",
                        to="chores.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("helper", models.F("owner")), _negated=True
                        ),
                        name="contributioncredit_helper_ne_owner",
                    )
                ],
            },
        ),
    ]
