# Generated by Django 5.1.15 on 2026-09-02 23:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_fairness_weights(apps, schema_editor):
    """Create a defaults row for any household that predates this model."""
    Household = apps.get_model("chores", "Household")
    FairnessWeights = apps.get_model("chores", "FairnessWeights")
    for household in Household.objects.filter(fairness_weights__isnull=True):
        FairnessWeights.objects.create(household=household)


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0007_choreoccurrence_claimed_by_contributioncredit"),
    ]

    operations = [
        migrations.CreateModel(
            name="FairnessWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Multiplies a chore's estimated minutes.",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "difficulty_weight",
                    models.FloatField(
                        default=1.0,
                        help_text="How far difficulty swings a chore's workload.",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "decay_half_life_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Days after which a past contribution counts for half.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fairness_weights",
                        to="chores.household",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "fairness weights",
            },
        ),
        migrations.RunPython(
            backfill_fairness_weights, migrations.RunPython.noop
        ),
    ]
