# Generated by Django 5.1.15 on 2026-09-03 00:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0008_fairnessweights"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstimateProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposed_minutes",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "proposed_difficulty",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Very easy"),
                            (2, "Easy"),
                            (3, "Moderate"),
                            (4, "Hard"),
                            (5, "Very hard"),
                        ],
                        null=True,
                    ),
                ),
                ("rationale", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimate_proposals",
                        to="chores.chore",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimate_decisions",
                        to="chores.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("chore",),
                        name="one_pending_estimate_proposal_per_chore",
                    )
                ],
            },
        ),
    ]
