# Generated by Django 5.1.15 on 2026-09-03 00:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0009_estimateproposal"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Multiplies a chore's estimated minutes.",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "difficulty_weight",
                    models.FloatField(
                        default=1.0,
                        help_text="How far difficulty swings a chore's workload.",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "decay_half_life_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Days after which a past contribution counts for half.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="weight_proposals_approved",
                        to="chores.membership",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weight_proposals_created",
                        to="chores.membership",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_proposals",
                        to="chores.household",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("household",),
                        name="one_open_weight_proposal_per_household",
                    )
                ],
            },
        ),
    ]
