# Generated by Django 5.1.15 on 2026-09-03 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0010_weightproposal"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISetupDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_response", models.JSONField()),
                ("chores", models.JSONField(blank=True, default=list)),
                ("constraints", models.JSONField(blank=True, default=list)),
                ("assignments", models.JSONField(blank=True, default=list)),
                ("reasoning", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("applied", "Applied")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_setup_drafts",
                        to="chores.household",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
    ]
