# Generated by Django 5.1.15 on 2026-09-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0011_aisetupdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="assignment_needs_review",
            field=models.BooleanField(
                default=False,
                help_text="Set when the primary owner came from an AI setup plan (task #19) and the members haven't confirmed it yet.",
            ),
        ),
    ]
